version: "3.8"

services:
  rec:
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
