version: "3.8"

services:
  rec:
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      RABBIT_PASSWORD: "A6oLg0mn0MZHWN0BsHAIh3OqYeohszpA"
      RABBIT_USER: "xjbiarkb"
      RABBIT_HOST: "bonobo.rmq.cloudamqp.com/xjbiarkb"
